#!/bin/bash


set -o pipefail

trap 'log_crash $?' ERR

log_crash() {
    DATE=$(date "+%Y-%m-%d %H:%M:%S.%3N")
    echo "[${DATE}] [CRITICAL] ${PROCESS_NAME:=unknown process} exited with error code ${1} (CRASH)"
    exit ${1}
}

log_error() {
    DATE=$(date "+%Y-%m-%d %H:%M:%S.%3N")
    echo "[${DATE}] [CRITICAL] $@"
    log_crash 1
}

[[ "${PROCESS_NAME}" ]] || log_error "PROCESS_NAME environment variable not set"

. /app/auros/bin/activate

# /app/auros/config will be cloned by an enclave init process.
python3 -u -m dex_proxy --process-name ${PROCESS_NAME} -c /app/auros/config/${PROCESS_NAME}.json -s

exit $?
