services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      # AMQP
      - "5672:5672"
      # Management UI
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

volumes:
  rabbitmq-data:
