# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bundle.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'bundle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62undle.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x97\x01\n\x14PWebsocketBundleArgs\x12\x0b\n\x03txs\x18\x01 \x03(\x0c\x12\x14\n\x0c\x62lock_number\x18\x02 \x01(\x04\x12\x1b\n\x13reverting_tx_hashes\x18\x03 \x03(\t\x12\x18\n\x10replacement_uuid\x18\x04 \x01(\t\x12\x12\n\nsession_id\x18\x05 \x01(\t\x12\x11\n\tclient_id\x18\x06 \x01(\x04\"c\n\x1aPWebsocketCancelBundleArgs\x12\x13\n\x0b\x63\x61ncel_type\x18\x01 \x01(\r\x12\x30\n\nsession_id\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bundle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PWEBSOCKETBUNDLEARGS']._serialized_start=49
  _globals['_PWEBSOCKETBUNDLEARGS']._serialized_end=200
  _globals['_PWEBSOCKETCANCELBUNDLEARGS']._serialized_start=202
  _globals['_PWEBSOCKETCANCELBUNDLEARGS']._serialized_end=301
# @@protoc_insertion_point(module_scope)
